'use client'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '@/lib/supabase-browser'
type Message={id:string;sender:'customer'|'agent'|'bot';body:string;created_at:string}
type Conversation={id:string;session_id:string;automation_stage:string;automation_paused:boolean;tracking_number?:string|null}
const SESSION_KEY='upc-support-session'
function getSession(){let id=localStorage.getItem(SESSION_KEY);if(!id){id=crypto.randomUUID();localStorage.setItem(SESSION_KEY,id)}return id}
export default function SupportAgent(){
 const supabase=useMemo(()=>createClient(),[]),[open,setOpen]=useState(false),[conversation,setConversation]=useState<Conversation|null>(null),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[typing,setTyping]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function loadMessages(id:string){const{data,error}=await supabase.from('support_messages').select('id,sender,body,created_at').eq('conversation_id',id).order('created_at',{ascending:true});if(!error)setMessages((data||[]) as Message[])}
 async function ensureConversation(){setError('');const sid=getSession();let{data,error}=await supabase.from('support_conversations').select('*').eq('session_id',sid).maybeSingle();if(error){setError('Unable to connect to Agent. Please try again.');return}if(!data){const created=await supabase.from('support_conversations').insert({session_id:sid,status:'open',automation_stage:'awaiting_tracking',automation_paused:false}).select('*').single();if(created.error){setError('Unable to start chat. Please try again.');return}data=created.data}if(data){setConversation(data as Conversation);const{data:existing}=await supabase.from('support_messages').select('id').eq('conversation_id',data.id).limit(1);if(!existing?.length)await supabase.from('support_messages').insert({conversation_id:data.id,sender:'bot',body:'Hello! I’m the UPC Support Agent. If you want to track your package, please send your tracking number.'});await loadMessages(data.id)}}
 useEffect(()=>{if(open)ensureConversation()},[open])
 useEffect(()=>{if(!conversation?.id)return;const timer=setInterval(async()=>{await loadMessages(conversation.id);const{data}=await supabase.from('support_conversations').select('*').eq('id',conversation.id).single();if(data)setConversation(data as Conversation)},1500);return()=>clearInterval(timer)},[conversation?.id])
 function quick(value:string){setText(value)}
 async function botMessage(body:string){await supabase.from('support_messages').insert({conversation_id:conversation!.id,sender:'bot',body});await loadMessages(conversation!.id)}
 async function send(){const value=text.trim();if(!value||!conversation||busy)return;setBusy(true);setError('');setText('');const inserted=await supabase.from('support_messages').insert({conversation_id:conversation.id,sender:'customer',body:value});if(inserted.error){setError('Message could not be sent. Please try again.');setText(value);setBusy(false);return}await supabase.from('support_conversations').update({updated_at:new Date().toISOString(),last_customer_message_at:new Date().toISOString()}).eq('id',conversation.id);await loadMessages(conversation.id);if(conversation.automation_stage==='agent_takeover'||conversation.automation_paused){setBusy(false);return}
 const candidate=value.toUpperCase().match(/[A-Z0-9][A-Z0-9-]{5,}/)?.[0]||''
 if(!candidate){setTyping(true);window.setTimeout(async()=>{await botMessage('Please provide your correct UPC tracking number.');setTyping(false);setBusy(false)},800);return}
 setTyping(true)
 const{data:packages,error:lookupError}=await supabase.rpc('get_tracking_package',{p_tracking_number:candidate})
 const valid=!!(!lookupError&&packages&&packages.length)
 if(!valid){window.setTimeout(async()=>{setTyping(false);await botMessage('Please provide the correct UPC tracking number. I can only check a registered UPC shipment number.');setBusy(false)},800);return}
 await supabase.from('support_conversations').update({tracking_number:candidate,automation_stage:'checking',updated_at:new Date().toISOString()}).eq('id',conversation.id)
 window.setTimeout(async()=>{await botMessage('Checking your tracking number……');await supabase.from('support_conversations').update({automation_stage:'agent_takeover',automation_paused:true,updated_at:new Date().toISOString()}).eq('id',conversation.id);setConversation(c=>c?{...c,tracking_number:candidate,automation_stage:'agent_takeover',automation_paused:true}:c);setTyping(false);setBusy(false)},1800)
 }
 return <><button className="agent-fab" onClick={()=>setOpen(v=>!v)} aria-label="Open UPC Agent">Agent</button>{open&&<aside className="agent-chat" aria-label="UPC Agent"><header><div><strong>UPC Agent</strong><small><span/> {conversation?.automation_stage==='agent_takeover'?'Agent ready to help':'Online · Ready to help'}</small></div><button onClick={()=>setOpen(false)} aria-label="Close">×</button></header><div className="agent-body">{error&&<div className="agent-message bot"><small>UPC Agent</small><div>{error}</div></div>}{messages.map(m=><div className={'agent-message '+m.sender} key={m.id}><small>{m.sender==='customer'?'You':'UPC Agent'}</small><div>{m.body}</div></div>)}{messages.length===1&&conversation?.automation_stage==='awaiting_tracking'&&<div className="agent-quick"><button type="button" onClick={()=>quick('I want to track my package')}>Track my package</button><button type="button" onClick={()=>quick('I need my delivery status')}>Delivery status</button><button type="button" onClick={()=>quick('I need help with my shipment')}>Shipment help</button><button type="button" onClick={()=>quick('I want to speak to an agent')}>Speak to an agent</button></div>}{typing&&conversation?.automation_stage==='checking'&&<div className="agent-message bot typing"><small>UPC Agent</small><div>Checking<span className="dots">...</span></div></div>}</div><form onSubmit={e=>{e.preventDefault();send()}} className="agent-input"><input value={text} onChange={e=>setText(e.target.value)} disabled={busy} placeholder={conversation?.automation_stage==='agent_takeover'?'Write your message…':'Enter your tracking number…'}/><button type="submit" disabled={busy||!text.trim()}>Send</button></form></aside>}</>}
