'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@/lib/supabase-browser'
type Message={id:string;sender:'customer'|'agent'|'bot';body:string;created_at:string}
type Conversation={id:string;session_id:string;automation_stage:string;automation_paused:boolean;tracking_number?:string|null}
const SESSION_KEY='upc-support-session'
function getSession(userId?:string|null){const key=userId?`${SESSION_KEY}:${userId}`:SESSION_KEY;let id=localStorage.getItem(key);if(!id){id=crypto.randomUUID();localStorage.setItem(key,id)}return id}
async function support(body:any){const response=await fetch('/api/support-chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Support chat request failed');return data}
async function getIdentity(){try{const s=createClient();const {data}=await s.auth.getUser();return data.user?.id||null}catch{return null}}
export default function SupportAgent(){
 const[open,setOpen]=useState(false),[conversation,setConversation]=useState<Conversation|null>(null),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[typing,setTyping]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[identity,setIdentity]=useState<string|null>(null),[sessionId,setSessionId]=useState(''),[automatedReplies,setAutomatedReplies]=useState(true)
 async function loadMessages(id:string,sid=sessionId){try{if(!sid)return;const data=await support({action:'messages',conversation_id:id,session_id:sid});setConversation(data.conversation as Conversation);setMessages((data.messages||[]) as Message[]);setAutomatedReplies(data.automated_replies_enabled!==false)}catch(error:any){setError(error.message||'Unable to load Agent messages.')}}
 async function ensureConversation(){setError('');try{const userId=await getIdentity();const sid=getSession(userId);setIdentity(userId);setSessionId(sid);const data=await support({action:'ensure',session_id:sid,user_id:userId});setConversation(data.conversation as Conversation);setMessages((data.messages||[]) as Message[]);setAutomatedReplies(data.automated_replies_enabled!==false)}catch(error:any){setError(error.message||'Unable to connect to Agent. Please try again.')}}
 useEffect(()=>{if(open)ensureConversation()},[open])
 useEffect(()=>{if(!conversation?.id||!sessionId)return;const timer=window.setInterval(()=>loadMessages(conversation.id,sessionId),1500);return()=>window.clearInterval(timer)},[conversation?.id,sessionId])
 function quick(value:string){setText(value)}
 async function botMessage(body:string){if(!automatedReplies)return;await support({action:'bot',conversation_id:conversation!.id,session_id:sessionId,user_id:identity,body});await loadMessages(conversation!.id,sessionId)}
 async function send(){const value=text.trim();if(!value||!conversation||!sessionId||busy)return;setBusy(true);setError('');setText('');try{const sent=await support({action:'send',conversation_id:conversation.id,session_id:sessionId,user_id:identity,body:value});setAutomatedReplies(sent.automated_replies_enabled!==false);await loadMessages(sent.conversation_id||conversation.id,sessionId);if(sent.automated_replies_enabled===false||conversation.automation_stage==='agent_takeover'||conversation.automation_paused){setBusy(false);return}
 const candidate=value.toUpperCase().match(/[A-Z0-9][A-Z0-9-]{5,}/)?.[0]||''
 if(!candidate){setTyping(true);window.setTimeout(async()=>{try{await botMessage('Please provide your correct UPC tracking number.')}finally{setTyping(false);setBusy(false)}},800);return}
 setTyping(true)
 const lookup=await support({action:'lookup',tracking_number:candidate})
 const valid=Array.isArray(lookup.packages)&&lookup.packages.length>0
 if(!valid){window.setTimeout(async()=>{try{await botMessage('Please provide the correct UPC tracking number. I can only check a registered UPC shipment number.')}finally{setTyping(false);setBusy(false)}},800);return}
 await support({action:'update',conversation_id:conversation.id,session_id:sessionId,patch:{tracking_number:candidate,automation_stage:'checking',updated_at:new Date().toISOString()}})
 window.setTimeout(async()=>{try{await botMessage('Checking your tracking number……');if(automatedReplies){const updated=await support({action:'update',conversation_id:conversation!.id,session_id:sessionId,patch:{automation_stage:'agent_takeover',automation_paused:true,updated_at:new Date().toISOString()}});setConversation(updated.conversation as Conversation)}}finally{setTyping(false);setBusy(false)}},1800)
 }catch(error:any){setError(error.message||'Message could not be sent. Please try again.');setText(value);setBusy(false)}}
 return <><button className="agent-fab" onClick={()=>setOpen(v=>!v)} aria-label="Open UPC Agent">Agent</button>{open&&<aside className="agent-chat" aria-label="UPC Agent"><header><div><strong>UPC Agent</strong><small><span/> {conversation?.automation_stage==='agent_takeover'?'Agent ready to help':'Online · Ready to help'}</small></div><button onClick={()=>setOpen(false)} aria-label="Close">×</button></header><div className="agent-body">{error&&<div className="agent-message bot"><small>UPC Agent</small><div>{error}</div></div>}{messages.map(m=><div className={'agent-message '+m.sender} key={m.id}><small>{m.sender==='customer'?'You':'UPC Agent'}</small><div>{m.body}</div></div>)}{messages.length===1&&conversation?.automation_stage==='awaiting_tracking'&&automatedReplies&&<div className="agent-quick"><button type="button" onClick={()=>quick('I want to track my package')}>Track my package</button><button type="button" onClick={()=>quick('I need my delivery status')}>Delivery status</button><button type="button" onClick={()=>quick('I need help with my shipment')}>Shipment help</button><button type="button" onClick={()=>quick('I want to speak to an agent')}>Speak to an agent</button></div>}{typing&&conversation?.automation_stage==='checking'&&automatedReplies&&<div className="agent-message bot typing"><small>UPC Agent</small><div>Checking<span className="dots">...</span></div></div>}</div><form onSubmit={e=>{e.preventDefault();send()}} className="agent-input"><input value={text} onChange={e=>setText(e.target.value)} disabled={busy} placeholder={conversation?.automation_stage==='agent_takeover'?'Write your message…':'Enter your tracking number…'}/><button type="submit" disabled={busy||!text.trim()}>Send</button></form></aside>}</>}
