'use client'
import {useEffect,useState} from 'react'
import {useRouter} from 'next/navigation'
import {createClient} from '@/lib/supabase-browser'

type Shipment={id:string;tracking_number:string;recipient_name:string|null;origin:string|null;destination:string|null;service:string|null;status:string;estimated_delivery:string|null;package_description:string|null;transport_mode:string|null}
type Alert={id:string;title:string;message:string;type:string;read_at:string|null;created_at:string}
const labels:Record<string,string>={processing:'Processing',in_transit:'In transit',at_hub:'At hub',out_for_delivery:'Out for delivery',delivered:'Delivered',exception:'Exception'}
export default function Dashboard(){const router=useRouter();const supabase=createClient();const[shipments,setShipments]=useState<Shipment[]>([]);const[alerts,setAlerts]=useState<Alert[]>([]);const[email,setEmail]=useState('');const[tracking,setTracking]=useState('');const[loading,setLoading]=useState(true);const[error,setError]=useState('')
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}setEmail(user.email||'');const[{data:sh,error:se},{data:al,error:ae}]=await Promise.all([supabase.rpc('get_my_shipments'),supabase.from('user_alerts').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(8)]);if(se)setError(se.message);if(ae)setError(ae.message);setShipments(sh||[]);setAlerts(al||[]);setLoading(false)})()},[router])
 async function saveTracking(e:React.FormEvent){e.preventDefault();const n=tracking.trim().toUpperCase();if(!n)return;const{error}=await supabase.from('user_saved_tracking').upsert({tracking_number:n,nickname:null},{onConflict:'user_id,tracking_number'});if(error){setError(error.message);return}router.push(`/track/${encodeURIComponent(n)}`)}
 async function signOut(){await supabase.auth.signOut();router.replace('/login')}
 if(loading)return <main className="container" style={{paddingTop:60}}><div className="card" style={{padding:32}}>Loading your UPC dashboard…</div></main>
 return <main className="container" style={{paddingTop:32,paddingBottom:80}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,marginBottom:28,flexWrap:'wrap'}}><div><div className="eyebrow">MY UPC</div><h1 style={{margin:'6px 0'}}>Welcome back</h1><p className="muted" style={{margin:0}}>{email}</p></div><button className="btn btn-light" onClick={signOut}>Sign out</button></div>
 <section className="card" style={{padding:24,marginBottom:20}}><div className="eyebrow">TRACK A PACKAGE</div><h2 style={{margin:'6px 0 14px'}}>Where is your package?</h2><form onSubmit={saveTracking} style={{display:'flex',gap:10,flexWrap:'wrap'}}><input style={{flex:1,minWidth:220}} value={tracking} onChange={e=>setTracking(e.target.value)} placeholder="Enter UPC tracking number"/><button className="btn btn-dark">Track package</button></form>{error&&<div className="error" style={{marginTop:12}}>{error}</div>}</section>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:14,marginBottom:20}}><div className="card" style={{padding:20}}><span className="muted">Active shipments</span><h2 style={{margin:'6px 0'}}>{shipments.filter(s=>s.status!=='delivered').length}</h2></div><div className="card" style={{padding:20}}><span className="muted">Delivered</span><h2 style={{margin:'6px 0'}}>{shipments.filter(s=>s.status==='delivered').length}</h2></div><div className="card" style={{padding:20}}><span className="muted">Unread alerts</span><h2 style={{margin:'6px 0'}}>{alerts.filter(a=>!a.read_at).length}</h2></div></div>
 <section><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:10}}><h2>My shipments</h2></div>{shipments.length===0?<div className="card" style={{padding:24}}><b>No shipments linked to your email yet.</b><p className="muted">When a UPC shipment is registered by an administrator using this email address, it will appear here automatically.</p></div>:shipments.map(s=><a key={s.id} href={`/track/${encodeURIComponent(s.tracking_number)}`} className="card" style={{display:'block',padding:20,marginBottom:12,textDecoration:'none',color:'inherit'}}><div style={{display:'flex',justifyContent:'space-between',gap:16,flexWrap:'wrap'}}><div><b>{s.tracking_number}</b><div className="muted" style={{marginTop:5}}>{s.origin||'—'} → {s.destination||'—'}</div></div><strong>{labels[s.status]||s.status}</strong></div><div className="muted" style={{marginTop:12}}>{s.service||'UPC service'}{s.estimated_delivery?` · Estimated ${new Date(s.estimated_delivery+'T00:00:00').toLocaleDateString()}`:''}</div></a>)}</section>
 <section style={{marginTop:30}}><h2>Alerts</h2>{alerts.length===0?<div className="card" style={{padding:24}}><p className="muted">Shipment alerts will appear here.</p></div>:alerts.map(a=><div key={a.id} className="card" style={{padding:18,marginBottom:10}}><b>{a.title}</b><p style={{margin:'6px 0'}}>{a.message}</p><small className="muted">{new Date(a.created_at).toLocaleString()}</small></div>)}</section></main>}
